/*
 * Decompiled with CFR 0.0.
 * 
 * Could not load the following classes:
 *  java.lang.Boolean
 *  java.lang.Class
 *  java.lang.Comparable
 *  java.lang.Float
 *  java.lang.IllegalArgumentException
 *  java.lang.Integer
 *  java.lang.Long
 *  java.lang.Object
 *  java.lang.String
 *  java.lang.StringBuilder
 *  java.util.Arrays
 *  java.util.Collection
 *  java.util.Collections
 *  java.util.HashMap
 *  java.util.List
 *  java.util.Map
 *  java.util.concurrent.TimeUnit
 */
package com.applovin.impl.sdk.b;

import com.applovin.impl.a.j;
import com.applovin.sdk.AppLovinAdSize;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;

/*
 * Illegal identifiers - consider using --renameillegalidents true
 */
public class b<T>
implements Comparable {
    public static final b<Boolean> Q;
    public static final b<String> R;
    public static final b<String> S;
    public static final b<String> T;
    public static final b<Boolean> U;
    public static final b<String> V;
    public static final b<String> W;
    public static final b<String> X;
    public static final b<String> Y;
    public static final b<Integer> Z;
    private static final List<?> a;
    public static final b<String> aA;
    public static final b<String> aB;
    public static final b<String> aC;
    public static final b<String> aD;
    public static final b<String> aE;
    public static final b<String> aF;
    public static final b<String> aG;
    public static final b<Integer> aH;
    public static final b<String> aI;
    public static final b<String> aJ;
    public static final b<String> aK;
    public static final b<Boolean> aL;
    public static final b<Integer> aM;
    public static final b<Boolean> aN;
    public static final b<String> aO;
    public static final b<Boolean> aP;
    public static final b<Boolean> aQ;
    public static final b<Boolean> aR;
    public static final b<Integer> aS;
    public static final b<Integer> aT;
    public static final b<Integer> aU;
    public static final b<Integer> aV;
    public static final b<Integer> aW;
    public static final b<Boolean> aX;
    public static final b<Integer> aY;
    public static final b<Integer> aZ;
    public static final b<Boolean> aa;
    public static final b<Boolean> ab;
    public static final b<Boolean> ac;
    public static final b<Boolean> ad;
    public static final b<Boolean> ae;
    public static final b<Boolean> af;
    public static final b<Boolean> ag;
    public static final b<Boolean> ah;
    public static final b<String> ai;
    public static final b<Boolean> aj;
    public static final b<Long> ak;
    public static final b<Boolean> al;
    public static final b<Boolean> am;
    public static final b<Boolean> an;
    public static final b<Boolean> ao;
    public static final b<Long> ap;
    public static final b<Long> aq;
    public static final b<Long> ar;
    public static final b<Long> as;
    public static final b<Long> at;
    public static final b<Long> au;
    public static final b<String> av;
    public static final b<String> aw;
    public static final b<String> ax;
    public static final b<String> ay;
    public static final b<String> az;
    private static final Map<String, b<?>> b;
    public static final b<Integer> bA;
    public static final b<Integer> bB;
    public static final b<String> bC;
    public static final b<String> bD;
    public static final b<String> bE;
    public static final b<String> bF;
    public static final b<String> bG;
    public static final b<String> bH;
    public static final b<String> bI;
    public static final b<String> bJ;
    public static final b<String> bK;
    public static final b<String> bL;
    public static final b<Boolean> bM;
    public static final b<String> bN;
    public static final b<String> bO;
    public static final b<String> bP;
    public static final b<String> bQ;
    public static final b<Boolean> bR;
    public static final b<String> bS;
    public static final b<String> bT;
    public static final b<String> bU;
    public static final b<String> bV;
    public static final b<Boolean> bW;
    public static final b<Boolean> bX;
    public static final b<Boolean> bY;
    public static final b<Boolean> bZ;
    public static final b<Integer> ba;
    public static final b<Integer> bb;
    public static final b<Integer> bc;
    public static final b<Integer> bd;
    public static final b<Integer> be;
    public static final b<Integer> bf;
    public static final b<Integer> bg;
    public static final b<Boolean> bh;
    public static final b<Boolean> bi;
    public static final b<Boolean> bj;
    public static final b<Boolean> bk;
    public static final b<Boolean> bl;
    public static final b<Boolean> bm;
    public static final b<Boolean> bn;
    public static final b<Boolean> bo;
    public static final b<Boolean> bp;
    public static final b<Boolean> bq;
    public static final b<Long> br;
    public static final b<Integer> bs;
    public static final b<String> bt;
    public static final b<Boolean> bu;
    public static final b<Boolean> bv;
    public static final b<Boolean> bw;
    public static final b<Boolean> bx;
    public static final b<Boolean> by;
    public static final b<String> bz;
    public static final b<Long> cA;
    public static final b<Boolean> cB;
    public static final b<Long> cC;
    public static final b<Boolean> cD;
    public static final b<Boolean> cE;
    public static final b<Boolean> cF;
    public static final b<Long> cG;
    public static final b<Integer> cH;
    public static final b<Integer> cI;
    public static final b<Integer> cJ;
    public static final b<Boolean> cK;
    public static final b<Integer> cL;
    public static final b<Boolean> cM;
    public static final b<Long> cN;
    public static final b<Long> cO;
    public static final b<Boolean> cP;
    public static final b<Integer> cQ;
    public static final b<Integer> cR;
    public static final b<Integer> cS;
    public static final b<Integer> cT;
    public static final b<Boolean> cU;
    public static final b<Integer> cV;
    public static final b<Integer> cW;
    public static final b<Integer> cX;
    public static final b<Integer> cY;
    public static final b<Integer> cZ;
    public static final b<String> ca;
    public static final b<Boolean> cb;
    public static final b<Boolean> cc;
    public static final b<Boolean> cd;
    public static final b<Boolean> ce;
    public static final b<Integer> cf;
    public static final b<Boolean> cg;
    public static final b<String> ch;
    public static final b<Integer> ci;
    public static final b<Integer> cj;
    public static final b<Integer> ck;
    public static final b<Integer> cl;
    public static final b<Integer> cm;
    public static final b<Long> cn;
    public static final b<Integer> co;
    public static final b<Integer> cp;
    public static final b<Integer> cq;
    public static final b<Integer> cr;
    public static final b<Integer> cs;
    public static final b<Integer> ct;
    public static final b<Float> cu;
    public static final b<Long> cv;
    public static final b<Long> cw;
    public static final b<Boolean> cx;
    public static final b<Long> cy;
    public static final b<Boolean> cz;
    public static final b<Integer> dA;
    public static final b<Boolean> dB;
    public static final b<Long> dC;
    public static final b<Boolean> dD;
    public static final b<Integer> dE;
    public static final b<Integer> dF;
    public static final b<Integer> dG;
    public static final b<Integer> dH;
    public static final b<Integer> dI;
    public static final b<Boolean> dJ;
    public static final b<Boolean> dK;
    public static final b<Integer> dL;
    public static final b<Integer> dM;
    public static final b<Integer> dN;
    public static final b<Boolean> dO;
    public static final b<Boolean> dP;
    public static final b<Boolean> dQ;
    public static final b<Boolean> dR;
    public static final b<Integer> dS;
    public static final b<Integer> dT;
    public static final b<Boolean> dU;
    public static final b<Integer> dV;
    public static final b<Integer> dW;
    public static final b<Integer> dX;
    public static final b<Integer> dY;
    public static final b<Integer> dZ;
    public static final b<Boolean> da;
    public static final b<Boolean> db;
    public static final b<Boolean> dc;
    public static final b<Boolean> dd;
    public static final b<Boolean> de;
    public static final b<Long> df;
    public static final b<Boolean> dg;
    public static final b<Long> dh;
    public static final b<Boolean> di;
    public static final b<Boolean> dj;
    public static final b<String> dk;
    public static final b<Boolean> dl;
    public static final b<Boolean> dm;
    public static final b<Boolean> dn;
    public static final b<Boolean> do;
    public static final b<Boolean> dp;
    public static final b<Boolean> dq;
    public static final b<Integer> dr;
    public static final b<Integer> ds;
    public static final b<Integer> dt;
    public static final b<Boolean> du;
    public static final b<Long> dv;
    public static final b<Integer> dw;
    public static final b<Integer> dx;
    public static final b<Long> dy;
    public static final b<Boolean> dz;
    public static final b<Boolean> eA;
    public static final b<Long> eB;
    public static final b<String> eC;
    public static final b<Boolean> eD;
    public static final b<Boolean> eE;
    public static final b<Integer> eF;
    public static final b<Integer> eG;
    public static final b<Integer> eH;
    public static final b<Boolean> eI;
    public static final b<Boolean> eJ;
    public static final b<Integer> eK;
    public static final b<String> eL;
    public static final b<String> eM;
    public static final b<Integer> eN;
    public static final b<Integer> eO;
    public static final b<Long> eP;
    public static final b<String> eQ;
    public static final b<String> eR;
    public static final b<Boolean> eS;
    public static final b<Integer> eT;
    public static final b<Integer> eU;
    public static final b<Integer> eV;
    public static final b<Boolean> eW;
    public static final b<Boolean> eX;
    public static final b<Boolean> eY;
    public static final b<Long> eZ;
    public static final b<Boolean> ea;
    public static final b<Boolean> eb;
    public static final b<Boolean> ec;
    public static final b<Integer> ed;
    public static final b<Boolean> ee;
    public static final b<Boolean> ef;
    public static final b<Long> eg;
    public static final b<Long> eh;
    public static final b<Boolean> ei;
    public static final b<Boolean> ej;
    public static final b<Boolean> ek;
    public static final b<String> el;
    public static final b<String> em;
    public static final b<Boolean> en;
    public static final b<Boolean> eo;
    public static final b<Boolean> ep;
    public static final b<Boolean> eq;
    public static final b<Boolean> er;
    public static final b<Boolean> es;
    public static final b<Boolean> et;
    public static final b<String> eu;
    public static final b<String> ev;
    public static final b<String> ew;
    public static final b<String> ex;
    public static final b<Boolean> ey;
    public static final b<Float> ez;
    public static final b<Long> fa;
    public static final b<Boolean> fb;
    public static final b<Boolean> fc;
    public static final b<Boolean> fd;
    public static final b<Boolean> fe;
    public static final b<Boolean> ff;
    public static final b<Boolean> fg;
    public static final b<Boolean> fh;
    public static final b<Boolean> fi;
    public static final b<Boolean> fj;
    public static final b<Boolean> fk;
    public static final b<Boolean> fl;
    public static final b<Boolean> fm;
    public static final b<Boolean> fn;
    public static final b<Long> fo;
    public static final b<Boolean> fp;
    public static final b<Boolean> fq;
    public static final b<String> fr;
    private final String c;
    private final T d;

    static {
        Object[] arrobject = new Class[5];
        Integer n2 = 0;
        Boolean bl = false;
        arrobject[0] = Boolean.class;
        Integer n3 = 1;
        Boolean bl2 = true;
        arrobject[1] = Float.class;
        arrobject[2] = Integer.class;
        arrobject[3] = Long.class;
        arrobject[4] = String.class;
        a = Arrays.asList((Object[])arrobject);
        b = new HashMap(512);
        Q = b.a("is_disabled", bl);
        R = b.a("device_id", "");
        S = b.a("publisher_id", "");
        T = b.a("device_token", "");
        U = b.a("is_verbose_logging", bl);
        V = b.a("sc", "");
        W = b.a("sc2", "");
        X = b.a("server_installed_at", "");
        Y = b.a("hash_algorithm", "SHA-1");
        Z = b.a("short_hash_size", 16);
        aa = b.a("trn", bl);
        ab = b.a("sp_apply", bl2);
        ac = b.a("honor_publisher_settings", bl2);
        ad = b.a("track_network_response_codes", bl);
        ae = b.a("submit_network_response_codes", bl);
        af = b.a("clear_network_response_codes_on_request", bl2);
        ag = b.a("clear_completion_callback_on_failure", bl);
        ah = b.a("publisher_can_show_consent_dialog", bl2);
        ai = b.a("consent_dialog_url", "https://assets.applovin.com/gdpr/flow_v1/gdpr-flow-1.html");
        aj = b.a("consent_dialog_immersive_mode_on", bl);
        ak = b.a("consent_dialog_show_from_alert_delay_ms", 450L);
        al = b.a("alert_consent_for_dialog_rejected", bl);
        am = b.a("alert_consent_for_dialog_closed", bl);
        an = b.a("alert_consent_for_dialog_closed_with_back_button", bl);
        ao = b.a("alert_consent_after_init", bl);
        ap = b.a("alert_consent_after_init_interval_ms", TimeUnit.MINUTES.toMillis(5L));
        aq = b.a("alert_consent_after_dialog_rejection_interval_ms", TimeUnit.MINUTES.toMillis(30L));
        ar = b.a("alert_consent_after_dialog_close_interval_ms", TimeUnit.MINUTES.toMillis(5L));
        as = b.a("alert_consent_after_dialog_close_with_back_button_interval_ms", TimeUnit.MINUTES.toMillis(5L));
        at = b.a("alert_consent_after_cancel_interval_ms", TimeUnit.MINUTES.toMillis(10L));
        au = b.a("alert_consent_reschedule_interval_ms", TimeUnit.MINUTES.toMillis(5L));
        av = b.a("text_alert_consent_title", "Make this App Better and Stay Free!");
        aw = b.a("text_alert_consent_body", "If you don't give us consent to use your data, you will be making our ability to support this app harder, which may negatively affect the user experience.");
        ax = b.a("text_alert_consent_yes_option", "I Agree");
        ay = b.a("text_alert_consent_no_option", "Cancel");
        az = b.a("fetch_settings_endpoint", "https://ms.applovin.com/");
        aA = b.a("fetch_settings_backup_endpoint", "https://ms.applvn.com/");
        aB = b.a("adserver_endpoint", "https://a.applovin.com/");
        aC = b.a("adserver_backup_endpoint", "https://a.applvn.com/");
        aD = b.a("api_endpoint", "https://d.applovin.com/");
        aE = b.a("api_backup_endpoint", "https://d.applvn.com/");
        aF = b.a("event_tracking_endpoint_v2", "https://rt.applovin.com/");
        aG = b.a("event_tracking_backup_endpoint_v2", "https://rt.applvn.com/");
        aH = b.a("bid_token_max_length", 3000);
        aI = b.a("token_type_prefixes_r", "4!");
        aJ = b.a("token_type_prefixes_arj", "json_v3!");
        aK = b.a("top_level_events", "landing,paused,resumed,checkout,iap");
        aL = b.a("events_enabled", bl2);
        aM = b.a("preload_callback_timeout_seconds", -1);
        aN = b.a("ad_preload_enabled", bl2);
        aO = b.a("ad_auto_preload_sizes", "");
        aP = b.a("ad_auto_preload_incent", bl2);
        aQ = b.a("ad_auto_preload_native", bl);
        aR = b.a("preload_native_ad_on_dequeue", bl);
        aS = b.a("preload_capacity_banner_regular", n2);
        aT = b.a("preload_capacity_mrec_regular", n2);
        aU = b.a("preload_capacity_leader_regular", n2);
        aV = b.a("preload_capacity_inter_regular", n2);
        aW = b.a("preload_capacity_inter_videoa", n2);
        aX = b.a("use_per_format_cache_queues", bl2);
        Integer n4 = 15;
        aY = b.a("extended_preload_capacity_banner_regular", n4);
        aZ = b.a("extended_preload_capacity_mrec_regular", n4);
        ba = b.a("extended_preload_capacity_leader_regular", n4);
        bb = b.a("extended_preload_capacity_inter_regular", n4);
        bc = b.a("extended_preload_capacity_inter_videoa", n4);
        bd = b.a("preload_capacity_zone", n3);
        be = b.a("preload_capacity_zone_native", n3);
        bf = b.a("extended_preload_capacity_zone", n4);
        bg = b.a("preload_capacity_native_native", n2);
        bh = b.a("preload_merge_init_tasks_inter_regular", bl);
        bi = b.a("preload_merge_init_tasks_inter_videoa", bl);
        bj = b.a("preload_merge_init_tasks_banner_regular", bl);
        bk = b.a("preload_merge_init_tasks_mrec_regular", bl);
        b.bl = b.a("preload_merge_init_tasks_leader_regular", bl);
        bm = b.a("preload_merge_init_tasks_zones", bl);
        bn = b.a("honor_publisher_settings_verbose_logging", bl2);
        bo = b.a("honor_publisher_settings_auto_preload_ad_sizes", bl2);
        bp = b.a("honor_publisher_settings_auto_preload_ad_types", bl2);
        bq = b.a("cache_cleanup_enabled", bl);
        br = b.a("cache_file_ttl_seconds", 86400L);
        bs = b.a("cache_max_size_mb", -1);
        bt = b.a("precache_delimiters", ")]',");
        bu = b.a("native_auto_cache_preload_resources", bl2);
        bv = b.a("android_require_external_storage_permission", bl2);
        bw = b.a("android_drop_nomedia", bl2);
        bx = b.a("ad_resource_caching_enabled", bl2);
        by = b.a("fail_ad_load_on_failed_video_cache", bl2);
        bz = b.a("resource_cache_prefix", "https://vid.applovin.com/,https://pdn.applovin.com/,https://img.applovin.com/,https://d.applovin.com/,https://assets.applovin.com/,https://cdnjs.cloudflare.com/,http://vid.applovin.com/,http://pdn.applovin.com/,http://img.applovin.com/,http://d.applovin.com/,http://assets.applovin.com/,http://cdnjs.cloudflare.com/");
        bA = b.a("vr_retry_count_v1", n3);
        bB = b.a("cr_retry_count_v1", n3);
        bC = b.a("text_incent_prompt_title", "Earn a Reward");
        bD = b.a("text_incent_prompt_body", "Would you like to watch a video for a reward?");
        bE = b.a("text_incent_prompt_yes_option", "Watch Now");
        bF = b.a("text_incent_prompt_no_option", "No Thanks");
        bG = b.a("text_incent_completion_title", "Video Reward");
        bH = b.a("text_incent_completion_body_success", "You have earned a reward!");
        bI = b.a("text_incent_completion_body_quota_exceeded", "You have already earned the maximum reward for today.");
        bJ = b.a("text_incent_completion_body_reward_rejected", "Your reward was rejected.");
        bK = b.a("text_incent_completion_body_network_failure", "We were unable to contact the rewards server. Please try again later.");
        bL = b.a("text_incent_completion_close_option", "Okay");
        bM = b.a("incent_warning_enabled", bl);
        bN = b.a("text_incent_warning_title", "Attention!");
        bO = b.a("text_incent_warning_body", "You won\u2019t get your reward if the video hasn\u2019t finished.");
        bP = b.a("text_incent_warning_close_option", "Close");
        bQ = b.a("text_incent_warning_continue_option", "Keep Watching");
        bR = b.a("incent_nonvideo_warning_enabled", bl);
        bS = b.a("text_incent_nonvideo_warning_title", "Attention!");
        bT = b.a("text_incent_nonvideo_warning_body", "You won\u2019t get your reward if the game hasn\u2019t finished.");
        bU = b.a("text_incent_nonvideo_warning_close_option", "Close");
        bV = b.a("text_incent_nonvideo_warning_continue_option", "Keep Playing");
        bW = b.a("show_incent_prepopup", bl2);
        bX = b.a("show_incent_postpopup", bl2);
        bY = b.a("video_callbacks_for_incent_nonvideo_ads_enabled", bl2);
        bZ = b.a("wrapped_zones", bl);
        ca = b.a("wrapped_sizes", "");
        cb = b.a("return_wrapped_ad_on_empty_queue", bl);
        cc = b.a("consider_wrapped_ad_preloaded", bl);
        cd = b.a("reuse_rendered_ad_if_non_dequeued", bl);
        ce = b.a("check_webview_has_gesture", bl);
        cf = b.a("close_button_touch_area", n2);
        cg = b.a("click_overlay_enabled", bl);
        ch = b.a("click_overlay_color", "#66000000");
        ci = b.a("click_tracking_retry_count_v1", 3);
        cj = b.a("click_tracking_retry_delay", 2000);
        Integer n5 = 10000;
        ck = b.a("click_tracking_timeout", n5);
        cl = b.a("android_click_spinner_size", 50);
        cm = b.a("android_click_spinner_style", 16973853);
        cn = b.a("viewability_adview_imp_delay_ms", TimeUnit.SECONDS.toMillis(1L));
        co = b.a("viewability_adview_banner_min_width", 320);
        cp = b.a("viewability_adview_banner_min_height", AppLovinAdSize.BANNER.getHeight());
        cq = b.a("viewability_adview_mrec_min_width", AppLovinAdSize.MREC.getWidth());
        cr = b.a("viewability_adview_mrec_min_height", AppLovinAdSize.MREC.getWidth());
        cs = b.a("viewability_adview_leader_min_width", 728);
        ct = b.a("viewability_adview_leader_min_height", AppLovinAdSize.LEADER.getWidth());
        cu = b.a("viewability_adview_min_alpha", Float.valueOf((float)10.0f));
        cv = b.a("viewability_timer_min_visible_ms", TimeUnit.SECONDS.toMillis(1L));
        cw = b.a("viewability_timer_interval_ms", 100L);
        cx = b.a("ad_refresh_enabled", bl2);
        cy = b.a("ad_refresh_seconds", 120L);
        cz = b.a("mrec_ad_refresh_enabled", bl2);
        cA = b.a("mrec_ad_refresh_seconds", 120L);
        cB = b.a("leader_ad_refresh_enabled", bl2);
        cC = b.a("leader_ad_refresh_seconds", 120L);
        cD = b.a("dismiss_expanded_adview_on_refresh", bl);
        cE = b.a("dismiss_expanded_adview_on_detach", bl);
        cF = b.a("contract_expanded_ad_on_close", bl2);
        cG = b.a("expandable_close_button_animation_duration_ms", 300L);
        cH = b.a("expandable_close_button_size", 27);
        Integer n6 = 10;
        cI = b.a("expandable_h_close_button_margin", n6);
        cJ = b.a("expandable_t_close_button_margin", n6);
        cK = b.a("expandable_lhs_close_button", bl);
        cL = b.a("expandable_close_button_touch_area", n2);
        cM = b.a("click_failed_expand", bl);
        cN = b.a("fullscreen_ad_pending_display_state_timeout_ms", TimeUnit.SECONDS.toMillis(10L));
        cO = b.a("fullscreen_ad_showing_state_timeout_ms", TimeUnit.MINUTES.toMillis(2L));
        cP = b.a("lhs_close_button_video", bl);
        cQ = b.a("close_button_right_margin_video", 4);
        cR = b.a("close_button_size_video", 30);
        cS = b.a("close_button_top_margin_video", 8);
        cT = b.a("close_fade_in_time", 400);
        cU = b.a("show_close_on_exit", bl2);
        cV = b.a("video_countdown_clock_margin", n6);
        cW = b.a("video_countdown_clock_gravity", 83);
        cX = b.a("countdown_clock_size", 32);
        cY = b.a("countdown_clock_stroke_size", 4);
        cZ = b.a("countdown_clock_text_size", 28);
        da = b.a("dismiss_video_on_error", bl2);
        db = b.a("draw_countdown_clock", bl2);
        dc = b.a("force_back_button_enabled_always", bl);
        dd = b.a("force_back_button_enabled_close_button", bl);
        de = b.a("force_back_button_enabled_poststitial", bl);
        df = b.a("force_hide_status_bar_delay_ms", 0L);
        dg = b.a("handle_window_actions", bl);
        dh = b.a("inter_display_delay", 200L);
        di = b.a("lock_specific_orientation", bl);
        dj = b.a("lhs_skip_button", bl2);
        dk = b.a("soft_buttons_resource_id", "config_showNavigationBar");
        dl = b.a("countdown_toggleable", bl);
        dm = b.a("mute_controls_enabled", bl);
        dn = b.a("allow_user_muting", bl2);
        do = b.a("mute_videos", bl);
        dp = b.a("show_mute_by_default", bl);
        dq = b.a("mute_with_user_settings", bl2);
        dr = b.a("mute_button_size", 32);
        ds = b.a("mute_button_margin", n6);
        dt = b.a("mute_button_gravity", 85);
        du = b.a("video_immersive_mode_enabled", bl);
        dv = b.a("progress_bar_step", 25L);
        dw = b.a("progress_bar_scale", n5);
        dx = b.a("progress_bar_vertical_padding", -8);
        dy = b.a("video_resume_delay", 250L);
        dz = b.a("is_video_skippable", bl);
        dA = b.a("vs_buffer_indicator_size", 50);
        dB = b.a("video_zero_length_as_computed", bl);
        dC = b.a("set_poststitial_muted_initial_delay_ms", 500L);
        dD = b.a("widget_fail_on_slot_count_diff", bl2);
        dE = b.a("native_batch_precache_count", n3);
        dF = b.a("submit_postback_timeout", n5);
        dG = b.a("submit_postback_retries", 4);
        dH = b.a("postback_service_max_queue_size", 100);
        dI = b.a("max_postback_attempts", 3);
        dJ = b.a("persistent_postback_manager_max_attempts_guard_fix", bl);
        dK = b.a("persistent_postback_manager_deserialization_exception_fix", bl);
        dL = b.a("get_retry_delay_v1", n5);
        dM = b.a("http_connection_timeout", 30000);
        dN = b.a("http_socket_timeout", 20000);
        dO = b.a("force_ssl", bl);
        dP = b.a("load_ads_if_no_internet", bl2);
        dQ = b.a("display_ads_if_no_internet", bl2);
        dR = b.a("network_available_if_none_detected", bl2);
        dS = b.a("fetch_ad_connection_timeout", 30000);
        dT = b.a("fetch_ad_retry_count_v1", n3);
        dU = b.a("submit_api_data_execute_immediately", bl);
        dV = b.a("submit_data_retry_count_v1", n3);
        dW = b.a("response_buffer_size", 16000);
        dX = b.a("fetch_basic_settings_connection_timeout_ms", 3000);
        dY = b.a("fetch_basic_settings_retry_count", 3);
        dZ = b.a("fetch_basic_settings_retry_delay_ms", 2000);
        ea = b.a("preload_persisted_zones", bl2);
        eb = b.a("persist_zones", bl2);
        ec = b.a("validate_zone_input", bl);
        ed = b.a("ad_session_minutes", 60);
        ee = b.a("session_tracking_enabled", bl);
        ef = b.a("session_tracking_cooldown_on_event_fire", bl2);
        eg = b.a("session_tracking_resumed_cooldown_minutes", 90L);
        eh = b.a("session_tracking_paused_cooldown_minutes", 90L);
        ei = b.a("track_app_paused", bl);
        ej = b.a("qq", bl);
        ek = b.a("qq1", bl2);
        el = b.a("plugin_version", "");
        em = b.a("fireos_manufacturer_list", "amazon");
        en = b.a("fireos_collect_google_idfa_on_fail", bl);
        eo = b.a("fireos_hide_adview_on_init", bl2);
        ep = b.a("fireos_load_empty_adview_on_init", bl);
        eq = b.a("hgn", bl);
        er = b.a("cit", bl);
        es = b.a("cso", bl);
        et = b.a("cfs", bl);
        eu = b.a("emulator_hardware_list", "ranchu,goldfish,vbox");
        ev = b.a("emulator_device_list", "generic,vbox");
        ew = b.a("emulator_manufacturer_list", "Genymotion");
        ex = b.a("emulator_model_list", "Android SDK built for x86");
        ey = b.a("adr", bl);
        ez = b.a("volume_normalization_factor", Float.valueOf((float)6.6666665f));
        eA = b.a("user_agent_collection_enabled", bl);
        eB = b.a("user_agent_collection_timeout_ms", 600L);
        eC = b.a("webview_package_name", "com.google.android.webview");
        eD = b.a("is_track_ad_info", bl2);
        eE = b.a("submit_ad_stats_enabled", bl);
        eF = b.a("submit_ad_stats_connection_timeout", 30000);
        eG = b.a("submit_ad_stats_retry_count", n3);
        eH = b.a("submit_ad_stats_max_count", 500);
        eI = b.a("task_stats_enabled", bl);
        eJ = b.a("error_reporting_enabled", bl);
        eK = b.a("error_reporting_log_limit", 100);
        eL = b.a("vast_image_html", "<html><head><style>html,body{height:100%;width:100%}body{background-image:url({SOURCE});background-repeat:no-repeat;background-size:contain;background-position:center;}a{position:absolute;top:0;bottom:0;left:0;right:0}</style></head><body><a href=\"applovin://com.applovin.sdk/adservice/track_click_now\"></a></body></html>");
        eM = b.a("vast_link_html", "<html><head><style>html,body,iframe{height:100%;width:100%;}body{margin:0}iframe{border:0;overflow:hidden;position:absolute}</style></head><body><iframe src={SOURCE} frameborder=0></iframe></body></html>");
        eN = b.a("vast_max_response_length", 640000);
        eO = b.a("vast_max_wrapper_depth", 5);
        eP = b.a("vast_progress_tracking_countdown_step", 1000L);
        eQ = b.a("vast_unsupported_video_extensions", "ogv,flv");
        eR = b.a("vast_unsupported_video_types", "video/ogg,video/x-flv");
        eS = b.a("vast_validate_with_extension_if_no_video_type", bl2);
        eT = b.a("vast_video_selection_policy", j.a.c.ordinal());
        eU = b.a("vast_wrapper_resolution_retry_count_v1", n3);
        eV = b.a("vast_wrapper_resolution_connection_timeout", 30000);
        eW = b.a("use_start_param", bl);
        eX = b.a("ree", bl2);
        eY = b.a("btee", bl2);
        eZ = b.a("server_timestamp_ms", 0L);
        fa = b.a("device_timestamp_ms", 0L);
        fb = b.a("immediate_render", bl);
        fc = b.a("cleanup_webview", bl);
        fd = b.a("sanitize_webview", bl);
        fe = b.a("force_rerender", bl);
        ff = b.a("video_view_should_use_system_on_measure", bl);
        fg = b.a("ignore_is_showing", bl);
        fh = b.a("dismiss_npe_check", bl);
        fi = b.a("rmp", bl);
        fj = b.a("notify_ad_load_listeners_on_main_thread", bl);
        fk = b.a("notify_ad_update_listeners_on_main_thread", bl);
        fl = b.a("detach_update_listener_on_pause", bl);
        fm = b.a("android_check_activity_is_finishing", bl);
        fn = b.a("synchronize_ad_object_access", bl);
        fo = b.a("count_down_interval_ms", 1000L);
        fp = b.a("render_empty_adview", bl2);
        fq = b.a("set_video_uri_background_thread", bl);
        fr = b.a("config_consent_dialog_state", "unknown");
    }

    public b(String string2, T t2) {
        if (string2 != null) {
            if (t2 != null) {
                this.c = string2;
                this.d = t2;
                return;
            }
            throw new IllegalArgumentException("No default value specified");
        }
        throw new IllegalArgumentException("No name specified");
    }

    protected static <T> b<T> a(String string2, T t2) {
        if (t2 != null) {
            if (a.contains((Object)t2.getClass())) {
                b<T> b2 = new b<T>(string2, t2);
                if (!b.containsKey((Object)string2)) {
                    b.put((Object)string2, b2);
                    return b2;
                }
                StringBuilder stringBuilder = new StringBuilder();
                stringBuilder.append("Setting has already been used: ");
                stringBuilder.append(string2);
                throw new IllegalArgumentException(stringBuilder.toString());
            }
            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.append("Unsupported value type: ");
            stringBuilder.append((Object)t2.getClass());
            throw new IllegalArgumentException(stringBuilder.toString());
        }
        throw new IllegalArgumentException("No default value specified");
    }

    public static Collection<b<?>> c() {
        return Collections.unmodifiableCollection((Collection)b.values());
    }

    T a(Object object) {
        return (T)this.d.getClass().cast(object);
    }

    public String a() {
        return this.c;
    }

    public T b() {
        return this.d;
    }

    public int compareTo(Object object) {
        if (object != null && object instanceof b) {
            String string2 = ((b)object).a();
            return this.c.compareTo(string2);
        }
        return 0;
    }
}

